let dados = [
    {
        nome: "Pedro",
        posicao: "Atacante",
        descricao: "Centroavante brasileiro conhecido por sua habilidade de finalização.",
        instagram: "https://www.instagram.com/pedroguilherme/",
        lesao: "Ruptura do ligamento cruzado anterior do joelho esquerdo.",
        tempoEstimadoRecuperacao: "6 meses",
        dataInicioLesao: "2024-09-04",
        tag:"9 queixo reverência"
    },
    {
        nome: "Matías Viña",
        posicao: "Lateral-esquerdo",
        descricao: "Lateral-esquerdo uruguaio conhecido por sua habilidade nos cruzamentos.",
        instagram: "https://www.instagram.com/matiasvina/",
        lesao: "Lesão no menisco do joelho direito.",
        tempoEstimadoRecuperacao: "4 meses",
        dataInicioLesao: "2024-08-11",
        tag: "uruguaio seleção uruguaia",
    },
    {
        nome: "Everton Cebolinha",
        posicao: "Atacante",
        descricao: "Atacante brasileiro conhecido por sua velocidade e habilidade de driblar.",
        instagram: "https://www.instagram.com/cebolinhaoficial/",
        lesao: "Ruptura do tendão de Aquiles.",
        tempoEstimadoRecuperacao: "8 meses",
        dataInicioLesao: "2024-08-11",
        tag: "atacante brasileiro velocidade drible"
    },
    {
        nome: "Gabigol",
        posicao: "Atacante",
        descricao: "Ídolo da torcida, artilheiro e referência técnica do time.",
        instagram: "https://www.instagram.com/gabigol/",
        lesao: "Lesão muscular",
        tempoEstimadoRecuperacao: "4 semanas",
        dataInicioLesao: "2024-08-15",
        tag: "hoje tem artilheiro",
     },
    {
        nome: "Giorgian de Arrascaeta",
        posicao: "Meia",
        descricao: "Meia armador de grande qualidade técnica, responsável por criar as principais jogadas do time.",
        instagram: "https://www.instagram.com/g10dearrascaeta/",
        lesao: "Lesão muscular",
        tempoEstimadoRecuperacao: "3 semanas",
        dataInicioLesao: "2024-08-20",
        tag: "uruguaio habilidade passes"
    },
    {
        nome: "Erick Pulgar",
        posicao: "Volante",
        descricao: "Volante chileno conhecido por sua força física e boa distribuição de bola.",
        instagram: "https://www.instagram.com/erickpulgar/",
        lesao: "Distensão muscular na coxa direita",
        tempoEstimadoRecuperacao: "3 semanas",
        dataInicioLesao: "2024-09-04",
        tag: "volante chileno seleção chilena desarme"
    },
    {
        nome: "Guillermo Varela",
        posicao: "Lateral-direito",
        descricao: "Lateral uruguaio com experiência em grandes clubes, conhecido por sua solidez defensiva.",
        instagram: "https://www.instagram.com/guillermovarela/",
        lesao: "Entorse no tornozelo esquerdo",
        tempoEstimadoRecuperacao: "2 semanas",
        dataInicioLesao: "2024-09-04",
        tag: "lateral seleção uruguaia",
    },
    {
        nome: "Nico De La Cruz",
        posicao: "Meia",
        descricao: "Meia uruguaio com grande visão de jogo e habilidade para criar jogadas.",
        instagram: "https://www.instagram.com/nicodelaruz/",
        lesao: "Lesão muscular na coxa esquerda",
        tempoEstimadoRecuperacao: "1 mês",
        dataInicioLesao: "2024-08-28",
        tag: "meia uruguaio drible",
    },
    {
        nome: "Michael",
        posicao: "Atacante",
        descricao: "Atacante rápido e habilidoso, conhecido por suas arrancadas e dribles.",
        instagram: "https://www.instagram.com/michaeloficial/",
        lesao: "Lesão muscular na coxa direita",
        tempoEstimadoRecuperacao: "3 semanas",
        dataInicioLesao: "2024-08-28",
        tag: "robozinho feio velocidade"
    },
    {
        nome: "Léo Pereira",
        posicao: "Zagueiro",
        descricao: "Zagueiro forte e seguro, com boa capacidade de desarme.",
        instagram: "https://www.instagram.com/leopereiraoficial/",
        lesao: "Entorse no joelho esquerdo",
        tempoEstimadoRecuperacao: "2 semanas",
        dataInicioLesao: "2024-08-31",
        tag: "zagueiro karolino carolino"
    },
];
